<a href="https://colab.research.google.com/github/jakphunn/DADS5001/blob/main/6610412008_as02_EPL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sklearn as sk

In [2]:
file_path = "https://raw.githubusercontent.com/jakphunn/test/main/2021-2022.csv"
df = pd.read_csv(file_path)
df.head(10)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
5,E0,14/08/2021,15:00,Leicester,Wolves,1,0,H,1,0,...,1.79,-0.75,2.02,1.91,2.01,1.92,2.05,1.95,1.99,1.89
6,E0,14/08/2021,15:00,Watford,Aston Villa,3,2,H,2,0,...,1.74,0.25,2.02,1.91,2.04,1.89,2.04,1.93,1.99,1.90
7,E0,14/08/2021,17:30,Norwich,Liverpool,0,3,A,0,1,...,2.48,1.25,1.85,2.08,1.85,2.09,2.03,2.10,1.88,2.01
8,E0,15/08/2021,14:00,Newcastle,West Ham,2,4,A,2,1,...,1.95,0.25,2.01,1.92,2.02,1.91,2.12,1.94,2.00,1.89
9,E0,15/08/2021,16:30,Tottenham,Man City,1,0,H,0,0,...,1.99,1.00,1.84,2.09,1.87,2.06,1.94,2.15,1.84,2.05

In [3]:
#Q1 show the top 3 teams that have the highest scores.

score = pd.DataFrame()

score['Team'] = pd.concat([df['HomeTeam'], df['AwayTeam']])
score['Goals'] = pd.concat([df['FTHG'], df['FTAG']])
total_goal = score.groupby('Team')['Goals'].sum().reset_index()
top3_team = total_goal.sort_values(by='Goals', ascending=False).head(3)

print("Top Three Teams with Highest Total Goals:")
print(top3_team.to_string(index=False))

Top Three Teams with Highest Total Goals:
     Team  Goals
 Man City     99
Liverpool     94
  Chelsea     76

In [4]:
#Q2 show the best home and away teams at shooting on target.

df['HSP'] = df['HST'] / df['HS']
df['ASP'] = df['AST'] / df['AS']

ht = df.loc[df['HSP'].idxmax()]['HomeTeam']
at = df.loc[df['ASP'].idxmax()]['AwayTeam']

print(f'Team with the highest shot precision as Home Team: {ht}')
print(f'Team with the highest shot precision as Away Team: {at}')

Team with the highest shot precision as Home Team: Aston Villa
Team with the highest shot precision as Away Team: West Ham

In [5]:
#Q3 how many times that Manchester United and Liverpool match each other in 2021-2022

lp = df[(df['HomeTeam'] == 'Liverpool') | (df['AwayTeam'] == 'Liverpool')]

mu = df[(df['HomeTeam'] == 'Man United') | (df['AwayTeam'] == 'Man United')]

lvsm = pd.concat([lp, mu])

print("Number of matches between Liverpool and Manchester United:", len(lvsm))

Number of matches between Liverpool and Manchester United: 76

In [6]:
#Q4 the results of Liverpool vs Man utd in 2021-2022

lp = df[(df['HomeTeam'] == 'Liverpool') & (df['AwayTeam'] == 'Man United')]

mu = df[(df['HomeTeam'] == 'Man United') & (df['AwayTeam'] == 'Liverpool')]

lvsm = pd.concat([lp, mu])

lp_stats = {
    'Wins': lvsm[lvsm['FTR'] == 'H'].shape[0],
    'Draws': lvsm[lvsm['FTR'] == 'D'].shape[0],
    'Losses': lvsm[lvsm['FTR'] == 'A'].shape[0]
}

mu_stats = {
    'Wins': lvsm[lvsm['FTR'] == 'A'].shape[0],
    'Draws': lvsm[lvsm['FTR'] == 'D'].shape[0],
    'Losses': lvsm[lvsm['FTR'] == 'H'].shape[0]
}

print("Liverpool Statistics:")
print(lp_stats)

print("\nManchester United Statistics:")
print(mu_stats)

Liverpool Statistics:
{'Wins': 1, 'Draws': 0, 'Losses': 1}

Manchester United Statistics:
{'Wins': 1, 'Draws': 0, 'Losses': 1}

In [7]:
#Q5 the top 3 teams that have the highest comeback rates in 2021-2022

cb_home = (df['HTR'] != 'H') & (df['FTR'] == 'H')
cb_away = (df['HTR'] == 'H') & (df['FTR'] == 'A')
cb_match = df[cb_home | cb_away]

cb_team = pd.concat([cb_match['HomeTeam'], cb_match['AwayTeam']])

cb_count = cb_team.value_counts()

total_match = pd.concat([df['HomeTeam'], df['AwayTeam']]).value_counts()
cb_rate = cb_count / total_match

top3_cb_team = cb_rate.nlargest(3)

print("Top 3 Teams with the Highest Comeback Rates:")
for team, rate in top3_cb_team.items():
    print(f"{team}: {rate:.2%}")

Top 3 Teams with the Highest Comeback Rates:
West Ham: 36.84%
Everton: 31.58%
Wolves: 28.95%